spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lookbook
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create